### ISSUE TITLE
[BUG] - termscp fails to compile on openSUSE with Rust 1.79

### ISSUE THREAD

**Issue by kastl-ars** [veeso/termscp#271]
## Description

I am trying to package termscp for openSUSE. Unfortunately it fails to compile (or maybe this is from bytesize, I am no Rust expert).

Or maybe I am missing something?

Kind Regards,
Johannes

```
[  344s]    Compiling content_inspector v0.2.4
[  345s]    Compiling whoami v1.5.1
[  345s]    Compiling version-compare v0.2.0
[  345s]    Compiling bytesize v1.3.0
[  359s] error[E0599]: no function or associated item named `new_multi_thread` found for struct `tokio::runtime::Builder` in the current scope
[  359s]    --> src/filetransfer/builder.rs:116:38
[  359s]     |
[  359s] 116 |             tokio::runtime::Builder::new_multi_thread()
[  359s]     |                                      ^^^^^^^^^^^^^^^^ function or associated item not found in `Builder`
[  359s]     |
[  359s] note: if you're trying to build a new `tokio::runtime::Builder` consider using one of the following associated functions:
[  359s]       tokio::runtime::Builder::new_current_thread
[  359s]       tokio::runtime::Builder::new
[  359s]    --> /home/abuild/rpmbuild/BUILD/termscp-0.14.0/vendor/tokio/src/runtime/builder.rs:217:5
[  359s]     |
[  359s] 217 |     pub fn new_current_thread() -> Builder {
[  359s]     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[  359s] ...
[  359s] 261 |     pub(crate) fn new(kind: Kind, event_interval: u32) -> Builder {
[  359s]     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[  359s] help: there is an associated function `new_current_thread` with a similar name
[  359s]     |
[  359s] 116 |             tokio::runtime::Builder::new_current_thread()
[  359s]     |                                      ~~~~~~~~~~~~~~~~~~
[  359s] 
[  360s] warning: use of deprecated method `tuirealm::tui::widgets::List::<'a>::start_corner`: You should use `List::direction` instead.
[  360s]   --> src/ui/activities/filetransfer/components/log.rs:66:14
[  360s]    |
[  360s] 66 |             .start_corner(Corner::BottomLeft)
[  360s]    |              ^^^^^^^^^^^^
[  360s]    |
[  360s]    = note: `#[warn(deprecated)]` on by default
[  360s] 
[  360s] warning: use of deprecated method `tuirealm::tui::widgets::List::<'a>::start_corner`: You should use `List::direction` instead.
[  360s]    --> src/ui/activities/filetransfer/components/transfer/file_list.rs:238:14
[  360s]     |
[  360s] 238 |             .start_corner(Corner::TopLeft);
[  360s]     |              ^^^^^^^^^^^^
[  360s] 
[  362s] For more information about this error, try `rustc --explain E0599`.
[  362s] warning: `termscp` (bin "termscp") generated 2 warnings
```

## Steps to reproduce

The build command use to start the compilation is something like this:

```
$ export CARGO_FEATURE_VENDORED=1
$ export RUSTFLAGS=' -Clink-arg=-Wl,-z,relro,-z,now -C debuginfo=2 -C incremental=false -C strip=none'
$ /usr/bin/cargo build -j4 --release
```

## Expected behaviour

The code should compile cleanly even on Rust 1.79

## Environment

- OS: openSUSE
- Architecture: multiple (x86, i586, aarch64, s390x, ...)
- Rust version 1.79
- termscp version 0.14.0

**Comment by veeso** [comment]
Can you retry now to build from main?

**Comment by kastl-ars** [comment]
I backported commit dfe58e6147f66b4c0c74874c954e7d101b3bf026 and started a build. This seems to have done the trick.

Thanks, that was quick!

I only get some deprecation warnings (and the tests are still running, but that is another topic):

```
[  317s]    Compiling remotefs-ssh v0.3.1
[  331s] warning: use of deprecated method `tuirealm::tui::widgets::List::<'a>::start_corner`: You should use `List::direction` instead.
[  331s]   --> src/ui/activities/filetransfer/components/log.rs:66:14
[  331s]    |
[  331s] 66 |             .start_corner(Corner::BottomLeft)
[  331s]    |              ^^^^^^^^^^^^
[  331s]    |
[  331s]    = note: `#[warn(deprecated)]` on by default
[  331s] 
[  331s] warning: use of deprecated method `tuirealm::tui::widgets::List::<'a>::start_corner`: You should use `List::direction` instead.
[  331s]    --> src/ui/activities/filetransfer/components/transfer/file_list.rs:238:14
[  331s]     |
[  331s] 238 |             .start_corner(Corner::TopLeft);
[  331s]     |              ^^^^^^^^^^^^
[  331s] 
[  351s] warning: `termscp` (bin "termscp") generated 2 warnings
[  351s]     Finished `release` profile [optimized] target(s) in 5m 18s
```

**Comment by veeso** [comment]
Okay, probably they got deprecated in the latest ratatui version. I'll fix that
